# Pre-commit Sample yaml template
# @see http://pre-commit.com/
default_language_version:
    python: python3.8
default_stages: [commit, push]
exclude: '^$'
fail_fast: false
repos:
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v3.1.0
      hooks:
          - id: check-added-large-files
          - id: check-byte-order-marker
          - id: check-case-conflict
          - id: check-docstring-first
          - id: check-json
          - id: check-merge-conflict
          - id: check-symlinks
          - id: check-xml
          - id: check-yaml
          - id: debug-statements
          - id: detect-aws-credentials
          - id: detect-private-key
          - id: double-quote-string-fixer
          - id: end-of-file-fixer
          - id: name-tests-test
          - id: pretty-format-json
          - id: requirements-txt-fixer
          - id: trailing-whitespace
    - repo: https://github.com/psf/black
      rev: stable
      hooks:
          - id: black
    - repo: https://gitlab.com/pycqa/flake8
      rev: 3.8.3
      hooks:
          - id: flake8
            additional_dependencies: [flake8-typing-imports==1.7.0]
            args: ['--max-line-length=79', '--ignore=E501']
    - repo: https://github.com/pre-commit/mirrors-autopep8
      rev: v1.5.3
      hooks:
          - id: autopep8
    - repo: https://github.com/pre-commit/mirrors-isort
      rev: v4.3.21
      hooks:
          - id: isort
            additional_dependencies: [toml]
            exclude: ^.*/?setup\.py$
    - repo: https://github.com/pre-commit/pre-commit
      rev: v2.6.0
      hooks:
          - id: validate_manifest
    - repo: https://github.com/asottile/reorder_python_imports
      rev: v2.3.2
      hooks:
          - id: reorder-python-imports
            args: [--py3-plus]
    - repo: https://github.com/asottile/pyupgrade
      rev: v2.7.1
      hooks:
          - id: pyupgrade
            args: [--py36-plus]
    - repo: https://github.com/asottile/add-trailing-comma
      rev: v2.0.1
      hooks:
          - id: add-trailing-comma
            args: [--py36-plus]
    - repo: https://github.com/asottile/setup-cfg-fmt
      rev: v1.11.0
      hooks:
          - id: setup-cfg-fmt
    - repo: https://github.com/pre-commit/mirrors-mypy
      rev: v0.782
      hooks:
          - id: mypy
    - repo: https://github.com/chriskuehl/puppet-pre-commit-hooks
      rev: v2.1.0
      hooks:
          - id: puppet-validate
          - id: puppet-lint
            args:
                [
                    --fix,
                    --fail-on-warnings,
                    --no-documentation-check,
                    --no-arrow_on_right_operand_line-check,
                ]
